### ISSUE TITLE
Not Able to Use Map in DynamoDB Entities

### ISSUE THREAD

**Issue by akefirad** [agorapulse/micronaut-aws-sdk#111]
Let's say I've got a very simple entity:
```kotlin
@Introspected
class DynamoDBEntity {
    @PartitionKey
    var parentId: String? = null
    @SortKey
    var id: String? = null
    var map: Map<String, List<String>>? = null
}
```
And the service:
```kotlin
@Service(value = DynamoDBEntity::class, tableName = "DynamoDBJava")
interface DynamoDBEntityService {
    fun save(entity: DynamoDBEntity): DynamoDBEntity
    fun load(@PartitionKey parentId: String, @SortKey id: String): DynamoDBEntity
}
```
Calling `save` like below:
```kotlin
dynamoDBEntityService.save(DynamoDBEntity().apply {
    parentId = randomUUID().toString()
    id = randomUUID().toString()
    map = mapOf("key" to listOf("value"))
})
```
Fails with:
```log
java.lang.IllegalStateException: Unsupported type: String K
	at software.amazon.awssdk.enhanced.dynamodb.EnhancedType.validateAndConvert(EnhancedType.java:524)
	at software.amazon.awssdk.enhanced.dynamodb.EnhancedType.<init>(EnhancedType.java:88)
	at software.amazon.awssdk.enhanced.dynamodb.EnhancedType.<init>(EnhancedType.java:96)
	at software.amazon.awssdk.enhanced.dynamodb.EnhancedType.of(EnhancedType.java:137)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.convertTypeToEnhancedType(BeanIntrospectionTableSchema.java:305)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.staticAttributeBuilder(BeanIntrospectionTableSchema.java:277)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.extractAttributeFromProperty(BeanIntrospectionTableSchema.java:237)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.lambda$createStaticTableSchema$2(BeanIntrospectionTableSchema.java:209)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.createStaticTableSchema(BeanIntrospectionTableSchema.java:211)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.schema.BeanIntrospectionTableSchema.create(BeanIntrospectionTableSchema.java:156)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.DefaultTableSchemaCreator.create(DefaultTableSchemaCreator.java:42)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.DefaultDynamoDBServiceProvider.lambda$findOrCreate$0(DefaultDynamoDBServiceProvider.java:73)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.DefaultDynamoDBServiceProvider.findOrCreate(DefaultDynamoDBServiceProvider.java:66)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.ServiceIntroduction.doIntercept(ServiceIntroduction.java:128)
	at com.agorapulse.micronaut.amazon.awssdk.dynamodb.ServiceIntroduction.intercept(ServiceIntroduction.java:98)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.example.DynamoDBEntityService$Intercepted.save(Unknown Source)
	at com.example.HomeController.index(HomeController.kt:13)
        ...
```
The issue seems to be in `BeanIntrospectionTableSchema#convertTypeToEnhancedType`:
```java
        if (List.class.equals(type.getType())) {
            EnhancedType<?> enhancedType = convertTypeToEnhancedType(type.getTypeParameters()[0], metaTableSchemaCache, attributeConfiguration, beanContext);
            return (EnhancedType<T>) EnhancedType.listOf(enhancedType);
        } else if (Map.class.equals(type.getType())) {
            EnhancedType<?> enhancedType = convertTypeToEnhancedType(type.getTypeParameters()[1], metaTableSchemaCache, attributeConfiguration, beanContext);
            return (EnhancedType<T>) EnhancedType.mapOf(EnhancedType.of(type.getTypeParameters()[0]), enhancedType);
        }
```
Unless I'm missing something, the code `EnhancedType.of(type.getTypeParameters()[0])` doesn't seem right, since the subsequent methods (specifically in aws-sdk) doesn't support `DefaultGenericPlaceholder` which the result of `type.getTypeParameters()[0]`.
[Here](https://github.com/agorapulse/micronaut-aws-sdk/files/9471630/test-dynamo.zip)'s a small project to reproduce it.

**Comment by musketyr** [comment]
Hi @akefirad, thanks for the report and especially for the reproducer. I will take a look next week and let you know.
